name: PHP with PHPUnit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: flexpay
        ports:
          - 3306:3306
        volumes:
          - dbdata:/var/lib/mysql

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up Docker Compose (use latest version)
      - name: Set up Docker Compose
        uses: docker/compose-action@v2  # Use latest stable version

      # Build and start containers with verbose output
      - name: Build and start containers with verbose output
        run: |
          sudo docker-compose -f docker-compose.yml up -d --build --force-recreate --remove-orphans 

      # Show Docker Compose logs for web service
      - name: Show Docker Compose logs for web
        run: |
          sudo docker-compose logs web

      # Wait for DB to be ready
      - name: Wait for DB to be ready
        run: |
          sudo docker-compose exec db bash -c 'until mysqladmin ping -h"localhost" --silent; do echo "Waiting for database"; sleep 5; done;'

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: |
          sudo docker-compose exec web vendor/bin/phpunit --configuration phpunit.xml --debug

      # Tear down containers
      - name: Shut down containers
        run: |
          sudo docker-compose down

